name: EX Emulators

on: [push, workflow_dispatch]

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["GBA.emu", "GBC.emu", "MD.emu", "NEO.emu", "NES.emu", "NGP.emu", "Snes9x"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y clang-15 cmake glibc-source flatpak flatpak-builder
        sudo apt install -y libasound2-dev libbluetooth-dev libboost-dev libdrm-dev libegl-dev
        sudo apt install -y libvorbis-dev libogg-dev libflac-dev
        sudo apt install -y libpulse-dev libxfixes-dev libxi-dev libxrandr-dev
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y --noninteractive flathub org.kde.Platform//5.15-22.08 org.kde.Sdk//5.15-22.08

    - name: Declare variables
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        mkdir repo
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV

    - name: Build bundled libraries
      run: |
        cd $IMAGINE_PATH/bundle/all/src/libarchive && make -f linux-x86_64.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build frameworks
      run: |
        make -f $IMAGINE_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk config -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build GBA.emu
      if: ${{ matrix.image == 'GBA.emu' }}
      run: |        
        cd GBA.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak GBA.emu
      if: ${{ matrix.image == 'GBA.emu' }}
      run: |        
        flatpak-builder --force-clean --repo=EX-Emulators/GBA --verbose build Flatpak/org.ExPlusAlpha.GBAemu.yml
        flatpak build-bundle --verbose Ex-Emulators/GBA GBAemu.flatpak org.ExPlusAlpha.GBAemu
        #cp repo/GBAemu/GBAemu.flatpak Ex-Emulators

    - name: Build GBC.emu
      if: ${{ matrix.image == 'GBC.emu' }}
      run: |        
        cd GBC.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak GBC.emu
      if: ${{ matrix.image == 'GBC.emu' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/GBC --force-clean --verbose Flatpak/org.ExPlusAlpha.GBCemu.yml

    - name: Build MD.emu
      if: ${{ matrix.image == 'MD.emu' }}
      run: |        
        cd MD.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak MD.emu
      if: ${{ matrix.image == 'MD.emu' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/MD --force-clean --verbose Flatpak/org.ExPlusAlpha.MDemu.yml    

    - name: Build NEO.emu
      if: ${{ matrix.image == 'NEO.emu' }}
      run: |        
        cd NEO.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak NEO.emu
      if: ${{ matrix.image == 'NEO.emu' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/NEO --force-clean --verbose Flatpak/org.ExPlusAlpha.NEOemu.yml  

    - name: Build NES.emu
      if: ${{ matrix.image == 'NES.emu' }}
      run: |        
        cd NES.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak NES.emu
      if: ${{ matrix.image == 'NES.emu' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/NES --force-clean --verbose Flatpak/org.ExPlusAlpha.NESemu.yml  

    - name: Build NGP.emu
      if: ${{ matrix.image == 'NGP.emu' }}
      run: |        
        cd NGP.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak NGP.emu
      if: ${{ matrix.image == 'NGP.emu' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/NGP --force-clean --verbose Flatpak/org.ExPlusAlpha.NGPemu.yml  

    - name: Build Snes9x.emu
      if: ${{ matrix.image == 'Snes9x' }}
      run: |        
        cd Snes9x
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Flatpak Snes9x
      if: ${{ matrix.image == 'Snes9x' }}
      run: |        
        flatpak-builder build-bundle --repo=EX-Emulators/Snes9x --force-clean --verbose Flatpak/org.ExPlusAlpha.Snes9x.yml  

    - name: Upload EX-Emulators artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: EX-Emulators
        path: EX-Emulators/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist
        file: Flatpak/install.sh

    - name: Re-zip artifacts
      run: |
        cd dist
        for artifact in *
        do 
          echo "-> Creating ${artifact}.zip"
          pushd "$artifact"
          zip -r "../${artifact}.zip" *
          popd
        done
    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: false
        tag: Pre-release
        artifacts: "dist/*.zip"
