name: EX Emulators

on: [push, workflow_dispatch]

jobs:
  build:
    name: Docker container
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
      options: --privileged
    strategy:
      matrix:
        image: ["GBA.emu", "GBC.emu", "MD.emu", "NEO.emu", "NES.emu", "NGP.emu", "Snes9x"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-15 cmake glibc-source
        sudo apt-get install -y libasound2-dev libbluetooth-dev libboost-dev libdrm-dev libegl-dev
        sudo apt-get install -y libflac-dev libvorbis-dev libogg-dev flatpak flatpak-builder
        sudo apt-get install -y libpulse-dev libxfixes-dev libxi-dev libxrandr-dev

    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        echo "EMUFRAMEWORK_PATH=/github/workspace/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=/github/workspace/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=/github/workspace/imagine-sdk" >> $GITHUB_ENV

    - name: Build bundled libraries
      run: |
        cd $IMAGINE_PATH/bundle/all/src/libarchive && make -f linux-x86_64.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk config -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build GBA.emu
      if: ${{ matrix.image == 'GBA.emu' }}
      uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: GBAemu.flatpak
        manifest-path: ../Flatpak/org.ExPlusAlpha.GBAemu.yml
