name: EX Emulators

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["GBA.emu", "GBC.emu", "MD.emu", "NEO.emu", "NES.emu", "NGP.emu", "Snes9x"]

    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y clang-15 cmake glibc-source
        sudo apt install -y libasound2-dev libbluetooth-dev libboost-dev libdrm-dev libegl-dev
        sudo apt install -y libvorbis-dev libogg-dev
        sudo apt install -y libpulse-dev libxfixes-dev libxi-dev libxrandr-dev

    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV

    - name: Bundled libraries
      run: |
        cd $IMAGINE_PATH/bundle/all/src/libarchive && make -f linux-x86_64.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk config -j2 CC=gcc-12 CXX=g++-12
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk install V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Build GBA.emu
      if: ${{ matrix.image == 'GBA.emu' }}
      run: |        
        cd GBA.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy GBA.emu artifact
      if: ${{ matrix.image == 'GBA.emu' }}
      run: |
        cp GBA.emu/target/linux/gbaemu EX-Emulators/GbaEmu

    - name: Upload GBA.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'GBA.emu' }}
      with: 
        name: GBAemu
        path: ${{ github.workspace }}/GBA.emu/target/linux/gbaemu

    - name: Build GBC.emu
      if: ${{ matrix.image == 'GBC.emu' }}
      run: |        
        cd GBC.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy GBC.emu artifact
      if: ${{ matrix.image == 'GBC.emu' }}
      run: |
        cp GBC.emu/target/linux/gbcemu EX-Emulators/GbcEmu

    - name: Upload GBC.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'GBC.emu' }}
      with: 
        name: GBCemu
        path: ${{ github.workspace }}/GBC.emu/target/linux/gbcemu

    - name: Build MD.emu
      if: ${{ matrix.image == 'MD.emu' }}
      run: |        
        cd MD.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy MD.emu artifact
      if: ${{ matrix.image == 'MD.emu' }}
      run: |
        cp MD.emu/target/linux/mdemu EX-Emulators/MdEmu

    - name: Upload MD.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'MD.emu' }}
      with: 
        name: MDemu
        path: ${{ github.workspace }}/MD.emu/target/linux/mdemu

    - name: Build NEO.emu
      if: ${{ matrix.image == 'NEO.emu' }}
      run: |        
        cd NEO.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy NEO.emu artifact
      if: ${{ matrix.image == 'NEO.emu' }}
      run: |
        cp NEO.emu/target/linux/neoemu EX-Emulators/NeoEmu

    - name: Upload NEO.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'NEO.emu' }}
      with: 
        name: NEOemu
        path: ${{ github.workspace }}/NEO.emu/target/linux/neoemu

    - name: Build NES.emu
      if: ${{ matrix.image == 'NES.emu' }}
      run: |        
        cd NES.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy NES.emu artifact
      if: ${{ matrix.image == 'NES.emu' }}
      run: |
        cp NES.emu/target/linux/nesemu EX-Emulators/NesEmu

    - name: Upload NES.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'NES.emu' }}
      with: 
        name: NESemu
        path: ${{ github.workspace }}/NES.emu/target/linux/nesemu

    - name: Build NGP.emu
      if: ${{ matrix.image == 'NGP.emu' }}
      run: |        
        cd NGP.emu
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy NGP.emu artifact
      if: ${{ matrix.image == 'NGP.emu' }}
      run: |
        cp NGP.emu/target/linux/ngpemu EX-Emulators/NgpEmu

    - name: Upload NGP.emu artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'NGP.emu' }}
      with: 
        name: NGPemu
        path: ${{ github.workspace }}/NGP.emu/target/linux/ngpemu

    - name: Build Snes9x.emu
      if: ${{ matrix.image == 'Snes9x' }}
      run: |        
        cd Snes9x
        make -f linux-x86_64-release.mk V=1 -j2 CC=gcc-12 CXX=g++-12

    - name: Copy Snes9x artifact
      if: ${{ matrix.image == 'Snes9x' }}
      run: |
        cp Snes9x/target/linux/s9xp EX-Emulators/Snes9xEXPlus

    - name: Upload Snes9x artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.image == 'Snes9x' }}
      with: 
        name: Snes9xEXPlus
        path: ${{ github.workspace }}/Snes9x/target/linux/s9xp

    - name: Upload EX-Emulators artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: EX-Emulators
        path: EX-Emulators/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Re-zip artifacts
      run: |
        cd dist
        for artifact in *
        do 
          echo "-> Creating ${artifact}.zip"
          pushd "$artifact"
          zip -r "../${artifact}.zip" *
          popd
        done
    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: false
        tag: Pre-release
        artifacts: "dist/*.zip"
